name: Format and Test

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - run: pip install black isort
    - run: black --check . --diff
    - name: If needed, commit black changes to a new pull request
      if: failure()
      run: |
        isort --profile black .
        black .
        git config --global user.name github-actions
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git commit -am "actions: auto-fmt"
        git push --force origin HEAD:$GITHUB_REF
